STACKPOT/STACKPOT-FE

package.json, src/App.tsx, src/components/commons/TextField/TextField.style.ts, src/components/layouts/Header/Header.style.ts, src/constants/routes.ts, src/main.tsx, src/pages/Home/Home.tsx, src/pages/Landing/Landing.tsx, src/pages/MyPage/MyPage.tsx, src/pages/NotFound/NotFound.tsx, src/pages/index.ts, src/routes/router.tsx, src/styles/theme.ts, yarn.lock
- close #6 
- 페이지 라우팅 설정
- 일단 페이지가 다 나온 게 아니라 임의로 라우팅 처리 진행했습니다. 나중에 디자인이 나오면 알맞게 추가하시면 됩니다. pages 폴더 구조도 기획이랑 디자인이 어느정도 나오고 다시 재조정이 필요할 것으로 예상됩니다.
=> [Feature/#6] 페이지 라우팅 설정

src/components/commons/Button/SignupButton.style.ts, src/components/commons/Button/SignupButton.tsx, src/components/forms/SelectableField/SelectableField.style.ts, src/components/forms/SelectableField/SelectableField.tsx, src/components/index.ts, src/styles/theme.ts
- close #10 
- 가입하기 버튼은 css 값들이 좀 달라서 theme으로 정의하기 어렵다고 생각하여 새로 만들었습니다
- 공개 범위 설정 컴포넌트 새로 나온거 구현했습니다
-
=> [Feature/#10] 공개 범위 설정, 가입하기 버튼 추가

src/styles/global.ts, src/styles/theme.ts
- close #17 
- theme.ts에 color 수정
- theme.ts에 font 수정사항 적용
- global.ts에 main 라벨 수정
- 아래 첫 번째, 두 번째 사진은 theme color 수정사항 잘 적용됐는지 테스트 해본 사진입니다
- 세 번째 사진은 width 908px, margin 0 auto 적용 잘됐는지 테스트 사진입니다
=> [Style/#17] theme - color, font 수정 / global main 라벨 수정

src/components/commons/Button/PotButton/PotButton.style.ts, src/components/commons/Button/PotButton/PotButton.tsx, src/components/index.ts
- close #29 
- '팟 관련 버튼' UI 구현
- 폰트 weight같은 경우에는 디자이너님이 문서에 적용안되있다고 하셔서 추후 작성해주시면 일괄적으로 적용될 예정입니당
https://github.com/user-attachments/assets/859d5837-0b36-4c18-b4d8-3225b39a2d09
=> [Feature/#29] 팟 관련 버튼 UI 구현

src/components/commons/Badge/CategoryButton/CategoryButton.style.ts, src/components/commons/Badge/CategoryButton/CategoryButton.tsx, src/components/commons/Button/PotButton/PotButton.style.ts, src/components/commons/Button/PotButton/PotButton.tsx
- close #34 
- 카테고리 버튼 onClick 속성 추가
- 팟 관련 버튼 style 추가, onClick 속성 추가
https://github.com/user-attachments/assets/d0e1d943-89e4-4ceb-8ceb-b57a683ade92
=> [Refactor/#34] 버튼 UI 및 로직 수정

src/components/commons/Modal/ExplainModal/ExplainModal.style.ts, src/components/commons/Modal/ExplainModal/ExplainModal.tsx, src/components/index.ts
- close #36 
- Explain 공통 모달 UI 구현
- children으로 tsx 코드를 전달하면 content에 표시됩니다
=> [Feature/#36] Explain 공통 모달 UI 구현

src/components/layouts/SideBar/SideBar.tsx
- close #38 
- pm님이 사이드바가 푸터 전에 멈추게 해달라고 하셔서 기능 추가했습니
-
=> [Feature/#38] 사이드바 푸터 전에 멈추게 하기

.github/workflows/title.yml, build.sh, vercel.json
- close #47 
- vercel.json 추가 및 GitHub Actions 워크플로우 설정
-
=> [Chore/#47] vercel.json 추가 및 GitHub Actions 워크플로우 설정

src/components/commons/Badge/MemberGroup/MemberGroup.tsx, src/components/commons/PotInformation/PotInformation.tsx, src/components/commons/TextField/TextField.style.ts, src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx, src/pages/Pots/AppliedPot/AppliedPot.tsx, src/pages/Pots/MadePot/MadePot.tsx, src/pages/SignUp/components/CategorySelection.tsx, src/pages/SignUp/components/ContractsSection.style.ts, src/pages/SignUp/components/ContractsSection.tsx, src/pages/SignUp/components/NicknameInput.style.ts
- close #80 
- 회원가입 페이지 스타일 수정
- 컴포넌트 map에 key값 설정
=> [Refactor/#80] 회원가입 텍스트필드 및 기타 컴포넌트 수정

src/apis/hooks/feeds/useGetFeeds.ts, src/apis/types/feed.ts, src/assets/svgs/index.ts, src/assets/svgs/loadingSpinner.svg, src/components/cards/PostCard/PostCard.style.ts, src/components/cards/PotCard/PotCard.style.ts, src/pages/Home/components/Feed/Feed.style.ts, src/pages/Home/components/Feed/Feed.tsx, src/pages/Home/components/PopularPots/PopularPots.tsx
- close #90 
- 무한스크롤 구현
- 스켈레톤 UI 추가
- 로딩처리 추가
- swiper 오류 수정
- 로딩처리 보려고 백엔드한테 응답 느리게 오게 해달라고 요청했고 기능 구현 완료하여 코드 없앨 예정입니다. 
- 스켈레톤 UI 지금은 안 예쁜데 추후 디자인 수정 작업 들어가겠습니다.
https://github.com/user-attachments/assets/c013b89d-ef5c-4bac-9bbf-1ad7ccdf1c67
=> [Feature/#90] 무한스크롤 구현

.gitignore, src/apis/hooks/users/useGetSignIn.ts, src/pages/Callback/Callback.style.ts, src/pages/Callback/Callback.tsx
- close #100 
- 회원가입 로직 수정
- 콜백 로딩처리
-
https://github.com/user-attachments/assets/3030928d-935a-49ad-ab84-6b57f50128cb
=> [Fix/#100] 회원가입 로직 수정

src/apis/hooks/myPots/useGetMyPot.ts, src/apis/hooks/searches/useGetSearch.ts, src/apis/myPotAPI.ts, src/apis/searchAPI.ts, src/apis/types/myPot.ts, src/components/cards/OnGoingPotCard/OnGoingPotCard.tsx, src/components/commons/Badge/MemberGroup/MemberGroup.tsx, src/constants/routes.ts, src/pages/MyPot/MyPot.style.ts, src/pages/MyPot/MyPot.tsx, src/pages/MyPot/MyPotMain.tsx, src/pages/MyPot/MyPotStatus/MyPotStatus.tsx, src/routes/router.tsx
- close #109 
- 나의 팟 첫 페이지 api 연결 
- 라우팅 방식 변경
- 나의 팟 라우팅 방식 약간 수정해서 참고 부탁드려요!
- 다른 페이지들도 이렇게 적용하면 좋을 거 같아요 ! constants에는 변하지 않는 값 상수화하는 거니까 router에서 하면 좋을 듯 싶습니다!
https://github.com/user-attachments/assets/04fe7ee1-5f73-4a2a-8d05-fbca1b56e1c4
=> [Feature/#109] 나의 팟 첫 페이지 api 연결 및 라우팅 방식 변경

src/apis/userAPI.ts, src/pages/SignUp/SignUp.tsx
- close #124 
- 회원가입 시 role이 반환되지 않는 문제 해결
-
=> [BugFix/#124] 회원가입 오류 수정

src/pages/SignUp/components/ProfileModal/ProfileModal.tsx, src/pages/UserPage/components/UserPageProfile.tsx
- close #132 
- 닉네임 생성 response 변경으로 인한 오류 수정
-
=> [Bugfix/#132] 닉네임 생성 response 오류 수정

src/apis/apiUtils.ts, src/apis/hooks/users/useDeleteUser.ts, src/apis/userAPI.ts, src/pages/PotDetail/PotDetail.tsx, src/pages/Setting/Setting.tsx
- close #134 
- 회원 탈퇴 api 연결
-
https://github.com/user-attachments/assets/62f864fc-47bd-4ffd-acb5-64ba782edfc6
=> [Featuere/#134] 회원 탈퇴 api 연결

package.json, src/App.tsx, src/apis/hooks/users/usePostNickname.ts, src/apis/hooks/users/userPostLogout.ts, src/providers/SnackbarProvider.tsx, src/providers/index.ts, yarn.lock
- close #143 
- 스낵바로 toast 기능 구현
- 로그아웃, 회원가입 완료 시에만 일단 적용했습니다. QA 후에 추가적으로 진행 예정입니다.
https://github.com/user-attachments/assets/5a0169f1-ab29-4bd3-96a3-628928b81e1d
=> [Feature/#143] 스낵바로 toast 기능 구현

src/apis/hooks/users/userPostLogout.ts
- close #146 
- 닉네임 오류 수정했습니다.
-
=> [Bugfix/#146] 닉네임 오류 수정

package.json, src/apis/hooks/feeds/usePatchFeed.ts, src/apis/hooks/feeds/usePostFeed.ts, src/apis/hooks/myPots/usePatchMyPotTodo.ts, src/apis/hooks/pots/useCreatePot.ts, src/apis/hooks/pots/usePatchPot.ts, src/components/layouts/Header/Header.tsx, src/pages/CreatePot/CreatePot.style.ts, src/pages/CreatePot/CreatePot.tsx, src/pages/CreatePot/components/PotForm.tsx, src/pages/EditPost/EditPost.tsx, src/pages/Landing/components/Step4/Step4.style.ts, src/pages/MyPot/MyPotStatus/MyPotStatus.style.ts, src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.style.ts, src/pages/MyPot/MyPotStatus/MyTodoModal/MyTodoModal.tsx, src/pages/MyPot/components/MyPotTodoCard/MyPotTodoCard.tsx, src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.style.ts, src/pages/PotDetail/components/ApplicantsInformation/ApplicantsInformation.tsx, src/pages/WritePost/WritePost.tsx, src/providers/SnackbarProvider.tsx, yarn.lock
- close #157 
- toast 기능 추가
- 헤더 클릭 이벤트 추가
-
https://github.com/user-attachments/assets/23515d8a-09d7-47ad-af9a-430a39469303
=> [Feature/#157] toast 기능 추가

src/assets/svgs/chevronRight.svg, src/assets/svgs/index.ts, src/components/commons/PotInformation/PotInformation.style.ts, src/components/commons/PotInformation/PotInformation.tsx, src/components/layouts/SideBar/SideBar.style.ts, src/pages/EditPot/EditPot.tsx, src/pages/Home/Home.tsx, src/pages/Home/components/PopularPots/PopularPots.tsx, src/pages/Home/components/index.ts, src/pages/Landing/Landing.style.ts, src/pages/Landing/Landing.tsx, src/pages/PotDetail/PotDetail.style.ts, src/pages/PotDetail/PotDetail.tsx, src/pages/PotDetail/components/PotHeader/PotHeader.style.ts, src/pages/PotDetail/components/PotHeader/PotHeader.tsx
- close #162 
- 랜딩 버튼 이벤트 수정
- 사이드바 z-index 수정
- 실시간 인기 팟 페이지네이션 수정
- 삭제 모달 스타일 수정
- 팟 디테일 모집 마감 추가 및 관련 스타일 수정
- 배너 버튼 클릭 시 로직 추가
- 팟 디테일 제목 스타일 수정
-
=> [Chore/#162] 1차 QA 진행

src/components/commons/Modal/Modal.style.ts
- close #174 
- 버튼 사이 값 변경
- 버튼과 본문 사이 값 변경
-
=> [Refactor/#174] 모달 스타일 변경

src/components/commons/PostFoam/PostFoam.tsx, src/pages/EditFinishedPot/EditFinishedPot.tsx, src/pages/Landing/Landing.tsx
- close #177 
- 피드 제목 글자 수 제한
- 랜딩 버튼 내용 변경 
-
=> [Refactor/#177] 피드제목 글자수 제한, 랜딩 버튼 내용 변경

src/components/cards/FinishedPotCard/FinishedPotCard.style.ts
=> [Refactor/#179] 밀림 현상 방지

src/pages/CreatePot/components/PotForm.tsx
- close #185 
- 팟 생성 폼 빈칸 제출 시 스낵바
필드 미입력시
https://github.com/user-attachments/assets/55c64fe5-a009-4eab-ac3b-e56708bec8f9
버튼 미선택시
https://github.com/user-attachments/assets/9c9ace75-cdae-4ca3-b5a4-de1a00127935
=> [Refactor/#185] 팟 생성 폼 빈칸 제출 시 스낵바 띄우기

src/apis/hooks/myPots/useGetMyPotTodo.ts, src/apis/hooks/users/useGetSignIn.ts, src/components/layouts/Header/Header.tsx, src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.tsx, src/pages/SignUp/SignUp.tsx, src/stores/useAuthStore.ts, src/types/role.ts
- close #191 
- 로그인 시 프로필 안 뜨는 문제 해결
-
=> [Bugfix/#191] 로그인 시 프로필 안 뜨는 문제 해결

src/apis/hooks/feeds/useDeleteFeed.ts, src/components/cards/PostCard/PostCard.tsx
- close #193 
- 비로그인 시 home 진입 불가 문제 해결
-
=> [Hotfix/#193] 비로그인 시 home 진입 불가 문제 해결

src/pages/FeedDetail/FeedDetail.tsx
- close #196 
- FeedDetail에 content에 개행 처
<div css={{ ...contentStyle, whiteSpace: 'pre-line' }}>
{data?.content}
</div>
이거 안돼서 다른 방식으로 햇습니다
=> [Feature/#196] Feed Detail 개행 문자 처리

src/apis/hooks/myPots/useDeleteMyPotTask.ts, src/apis/hooks/myPots/useGetMyPotTaskDetail.ts, src/apis/hooks/myPots/usePatchMyPotTodo.ts, src/components/cards/TaskCard/TaskCard.tsx, src/pages/MyPot/MyPotStatus/AboutWorkModal/AboutWorkModal.tsx, src/pages/MyPot/MyPotStatus/TaskDetail/TaskDetail.tsx
- close #198 
- TaskDetail, AboutWorkModal, TaskCard, DELETE api 리팩토링
-
=> [Refactor/#198] 나의팟 수정 삭제 수정

src/pages/Home/Home.tsx, src/pages/MyPot/MyPotCalendar/MyPotCalendar.style.ts
- close #200 
- 홈 배너 문구 띄어쓰기
- 캘린더 스타일 수정
-
=> [Refactor/#200] 홈 배너 문구 띄어쓰기

src/styles/theme.ts
- close #203
- Typography 수정
- Color, Shadow 수정
- 기존 디자인 시스템 과 신규 디자인 시스템 병합
=> [Refactor/#203] 디자인시스템 수정

src/components/cards/CtaCard/CtaCard.style.ts, src/components/cards/CtaCard/CtaCard.tsx, src/components/commons/Button/Button.style.ts, src/components/commons/Button/Button.tsx, src/components/index.ts, src/pages/Home/Home.tsx
- close #210
- 피드 작성 바로가기 컴포넌트(CtaCard) 구현
- cta 버튼 스타일 수정
- 드롭다운과 피드 카테고리 선택은 민수님 코드 반영하는 걸로..
https://github.com/user-attachments/assets/82052abb-8066-4a55-9e11-e1fa5926f062
=> [Feature/#210] 피드 작성 바로가기 컴포넌트 구현

vite.config.ts
=> [Feature/ 218] CI/CD  구현

src/apis/types/user.ts, src/components/commons/Button/PotButton/PotButton.style.ts, src/components/commons/Modal/ExplainModal/ExplainModal.style.ts, src/pages/Setting/Setting.style.ts, src/pages/Setting/Setting.tsx, src/pages/Setting/components/CategorySelection.style.ts, src/pages/Setting/components/CatetorySelection.tsx, src/pages/Setting/components/RoleUpdate.style.ts, src/pages/Setting/components/RoleUpdate.tsx, src/pages/Setting/components/index.ts
#221
- close #
-  설정 페이지 뷰 수정
- 추후 API 연동
=> [Feature/#221] 설정페이지 화면 수정

src/components/cards/MemberCard/MemberCard.tsx, src/pages/MyPotDetail/MyPotDetail.style.ts, src/pages/MyPotDetail/MyPotDetail.tsx, src/pages/MyPotDetail/components/SelectTaskMemberModal/SelectTaskMemberModal.style.ts
- close #281 
- 권한 위임 모달 구현
- 수정/ 권한 위임 버튼 추가
- 일단 퍼블리싱 진행했고, 백엔드 답변 오는대로 API 연결 예정입니다.
https://github.com/user-attachments/assets/b352a129-601b-4b4d-9fcc-cc008d5da8d4
=> [Feature/#281] 버튼 추가 및 권한 위임 모달 퍼블리싱

src/apis/hooks/users/useGetNickname.ts, src/apis/types/user.ts, src/apis/userAPI.ts, src/pages/SignUp/SignUp.tsx, src/pages/SignUp/components/CategorySelection/CategorySelection.tsx, src/pages/SignUp/components/ProfileModal/ProfileModal.tsx
=> [Refactor/#296] 회원가입 로직 수정
